#!/usr/bin/env ruby
# -*- coding: utf-8 -*-

# Does email address obfuscation actually work? Yes, when we use "display:none".
# http://superuser.com/questions/235937/does-email-address-obfuscation-actually-work

def tag_email(e)
  user, host = e.text.split(/\@/)
  e.text = ''
  return Text.new(user), Element.newer(:name => 'span', :attributes => "display:none", :text => '*'), Text.new(host)
end
